; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

board_build.mcu = atmega2560
board_build.f_cpu = 16000000L
upload_protocol = wiring

upload_flags = -D
upload_port = /dev/ttyUSB0
build_flags = -Wl,-u,vfprintf -lprintf_flt

; debug_tool = simavr
; build_type = debug
; debug_build_flags = -O0 -g3 -ggdb3
; debug_svd_path = ATmega2560.svd